--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/DctxGamesGB/Bossbars
build-by-default: true
branches:
- main
projects:
  Bossbars:
    path: ""
    model: virion
    type: library
...
